version: "3.9"
services:
  node_exporter:
    image: prom/node-exporter:v1.4.0 # a.r.r/ext-rbru-techimage-docker/node-exporter:v0.18.1
    networks:
      - app_monitoring
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'

  prometheus:
    image: prom/prometheus:v2.39.1 # a.r.r/ext-rbru-techimage-docker/prometheus:v2.11.0
    networks:
      - app_monitoring
    ports:
      - "9090:9090"
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:z'

  grafana:
    image: grafana/grafana:9.2.3 # a.r.r/ext-rbru-techimage-docker/grafana:6.4.3
    networks:
      - app_monitoring
    ports:
      - "3000:3000"

#  app:
#    build: ../../roles/target_app/files
#    image: ekr26/demo-app:1.0.0
#    networks:
#      - app_monitoring
#    ports:
#      - "8080:8080"
#      - "9999:9999"

networks:
  app_monitoring:
