global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s

scrape_configs:
- job_name: 'node_exporter'
  static_configs:
  - targets: ["host.containers.internal:9100"]

- job_name: 'app'
  metrics_path: '/dbo/actuator/prometheus'
  static_configs:
  - targets: ["host.containers.internal:8080"]
